apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-fastapi
  labels:
    app: langgraph-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langgraph-fastapi
  template:
    metadata:
      labels:
        app: langgraph-fastapi
    spec:
      containers:
      - name: langgraph-fastapi
        image: quay.io/jonkey/langgraph-fastapi:1.0.5
        imagePullPolicy: Always
        env:
        - name: LLAMA_STACK_BASE_URL
          value: http://llamastack-distribution-service:8321
        - name: API_KEY
          value: "fake"
        - name: ALLOWED_MODELS
          value: "vllm/qwen3-8b,openrouter/nvidia/nemotron-3-nano-30b-a3b:free"
        - name: TAVILY_SEARCH_API_KEY
          value: ""

        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
